### ISSUE TITLE
Exchange token from browser client

### ISSUE THREAD

**Issue by matteosuppo** [ory-am/hydra#107]
Imagine I have a browser application which receives the authorization code:

```
http://localhost:3000/?code=gr4HgnkhvIolSEQRBjFA-ipfugGngqoEl9NNzOkf5OQ.WfQumSAgUTD7OkfZgn8cXR8iUJCY_GfM2jVEut87OA4&scope=core&state=statestate
```

Is there a way to obtain an access token without authenticating with the client_id and client_secret?

**Comment by arekkas** [comment]
Yes, that is called the "implicit flow": https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2 (ctrl+f -> "Grant Type: Implicit")

**Comment by matteosuppo** [comment]
Oh, perfect, thank you

**Comment by arekkas** [comment]
Welcome
