### ISSUE TITLE
Connect to rethinkdb over SSL with self-signed certificate

### ISSUE THREAD

**Issue by matteosuppo** [ory-am/hydra#114]
Over at compose they provide rethinkdb servers with self-signed certificates.

You can connect to them in this way: https://www.compose.io/articles/rethinkdb-and-ssl-think-secure/

basically by reading a certificate

```go
    roots := x509.NewCertPool()
    cert, err := ioutil.ReadFile("./cacert")
    roots.AppendCertsFromPEM(cert)
```

and connecting with the TLS

```go
    session, err := r.Connect(r.ConnectOpts{
        Address:  "aws-eu-west-1-portal.1.dblayer.com:10605",
        Database: "test",
        AuthKey:  "QBXORIDHnnjkvUyhexl1nKcnAxbIqPBcrHeqkWglXc",
        TLSConfig: &tls.Config{
            RootCAs: roots,
        },
    })
```

I'm going to try to make it work. Are you interested in a Pull Request?

**Comment by arekkas** [comment]
Yes, please use the JWK Store for storing the RootCA. Setting custom RootCAs is also quite dangerous and we should anticipate problems there. Using the JWK Store only trusted clients could update those CAs, so that's a first good step.

**Comment by arekkas** [comment]
And I want to keep the number of configuration and env options low :)

**Comment by arekkas** [comment]
If you need help with the JWK store let me know

**Comment by matteosuppo** [comment]
Aren't JWK stored in rethinkdb?

**Comment by arekkas** [comment]
Haha wow, I didn't think that one through. Spot on.

**Comment by arekkas** [comment]
Ok let's make it work then like the HTTP TLS certificates (CLI option and env var)

**Comment by matteosuppo** [comment]
I'm working on it

**Comment by arekkas** [comment]
that's actually better because compromise of a priviledged client would not allow for the rootca to be changed or read
