### ISSUE TITLE
Showcase: How and where are you using Hydra?

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#115]
I want to introduce a showcase in the readme. If you're actively using Hydra let me know here. It will add a little SEO value to your website too :)

**Comment by matteosuppo** [comment]
https://www.arduino.cc (especially for services such as https://create.arduino.cc)

We aren't using it yet, but we're planning to migrate our current authentication system to oauth2 using hydra.

**Comment by arekkas** [comment]
Cool, let me know when you made it and I'll add you to the list :)

**Comment by arekkas** [comment]
It doesn't really look like this issue get's a lot of attention. I am therefore closing it.
