### ISSUE TITLE
hydra 2FA on cloud providers

### ISSUE THREAD

**Issue by fnzv** [ory-am/hydra#132]
I read a little the documentation but i couldn't figure it out so i'm asking:
Is it possible to configure 2FA with hydra on multiple servers(also on different cloud providers? aws,openstack..) for SSH access?

**Comment by arekkas** [comment]
Hydra currently doesn't support 2FA but if it where it would work in a distributed environment, as long as they are backed by the same rethinkdb instance. If you have the ability to check an HTTP api for the 2fa steps, this should work.

**Comment by fnzv** [comment]
Okk.. there is a web ui\dashboard to manage users? in the features i saw this : Real Time monitoring, with this feature is it possible to trace every API request? (Audit logging)

**Comment by arekkas** [comment]
No, hydra does not provide Identity Provider capabilities. The real time monitoring is the rethinkdb admin ui, which supports real time monitoring. I suggest to read the [guide](https://www.gitbook.com/read/book/ory-am/hydra) and [http api documentation](http://docs.hdyra.apiary.io/).

**Comment by arekkas** [comment]
2FA support is tracked as #69
