### ISSUE TITLE
Warden for anonymous users

### ISSUE THREAD

**Issue by matteosuppo** [ory-am/hydra#139]
Suppose I have a policy that allows anyone, including anonymous users, to access a resource.
Given that the user is anonymous I don't have a token, but the `ActionAllowed` method asks for it:

```
func (w *HTTPWarden) ActionAllowed(ctx context.Context, token string, a *ladon.Request, scopes ...string) (*Context, error) {
```

What should I do in this case?

**Comment by arekkas** [comment]
right, we need to add a simple policy check as well!

**Comment by arekkas** [comment]
This issue is now superseded by #162
