### ISSUE TITLE
Fails to startup when a SSO connection is added.

### ISSUE THREAD

**Issue by faxal** [ory-am/hydra#141]
Because `hydra_policies` table is used for `connections` also. Ladon errors when it tries to decode conditions. 

https://github.com/ory-am/ladon/blob/63d3e27a44b7e60f0cfd8a38231ccbe13c74aee7/manager_rethink.go#L40

**Comment by arekkas** [comment]
whoops, that's a typo here: https://github.com/ory-am/hydra/blob/master/cmd/server/handler_connection_factory.go#L26

**Comment by faxal** [comment]
Ah, makes sense. Seemed weird to me too, but rationalized that you might be trying to save a bit of memory by reducing number of tables as it has a small overhead.

**Comment by arekkas** [comment]
no, just me not paying attention :D
