### ISSUE TITLE
OpenID Connect Session Management 

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#143]
We should Implement session management that conforms to this spec:
https://openid.net/specs/openid-connect-session-1_0.html

**Comment by arekkas** [comment]
I have not looked through the specification yet, but it might well be possible that openid session management is targeted at RP and IDP instead of the AP. I will have to dig through the documentation.

If you find good material on this topic, please let me know.

**Comment by arekkas** [comment]
This specification is using iframes and stuff, I'm not confident that it's a good way forward. What do you think @janekolszak ?

**Comment by arekkas** [comment]
closing due to missing response and questionable draft
