### ISSUE TITLE
Make client HTTPManager not compatible with fosite.Storage

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#173]
Right now, HTTPManager returns the `fosite.Client` interface. As @boyvinall and @skymeyer pointed out, this is cumbersome when consuming the SDK. Since the HTTPManager isn't consumed by fosite and probably never will be, we could break compatibility with the `fosite.Storage` interface for it. This however might introduce some difficulties when [testing the various managers](https://github.com/ory-am/hydra/blob/master/client/manager_test.go#L28-L36).

Let me know what you think.

**Comment by arekkas** [comment]
Another way could be to add something like `GetRawClient` (better naming wanted) to the HTTPManager.

**Comment by arekkas** [comment]
@boyvinall @skymeyer please check if this works for you and let me know if you have suggestions for improvement: https://github.com/ory-am/hydra/pull/165/commits/01e6ae2dd346e5032f38a79e0e009de4c4007fc5

**Comment by skymeyer** [comment]
Looks good to me @arekkas  :+1:

**Comment by arekkas** [comment]
perfect
