### ISSUE TITLE
support edge tls termination

### ISSUE THREAD

**Issue by ibotty** [ory-am/hydra#177]
For deployment in kubernetes/openshift and similar environment it makes sense to support edge tls termination: Hydra would not terminate TLS itself but trust HTTP headers (e.g. X-Forwarded-Protocol).

**Comment by arekkas** [comment]
right now you can force hydra to disable https using `--force-dangerous-http`

**Comment by arekkas** [comment]
HTTP headers shouldn't really be trusted unless those security sensitive parameters can't be spoofed. we could add something like `trust-http-headers` or `edge-tls-termination` but

* you can already disable https with `--force-dangerous-http`
* `X-Forwarded-Protocol` is not a standard header and might vary from proxy to proxy. AWS for example uses `X-Forwarded-Proto`

**Comment by ibotty** [comment]
I am aware of the security implications of trusting headers: I am not advocating blindly trusting them. In a way, an edge-tls-termination flag is different from force-dangerous-http, because hydra would still generate only https-links. Also logging the right IP (from e.g. X-Forwarded-IP) is only necessary then.

(BTW: Of course, all X- headers are non-standard. Unfortunately the standard PROXY header support is not widespread yet).

**Comment by arekkas** [comment]
> an edge-tls-termination flag is different from force-dangerous-http, because hydra would still generate only https-links.

This is a very good point and I classified it as a bug.

> (BTW: Of course, all X- headers are non-standard. Unfortunately the standard PROXY header support is not widespread yet).

How could we solve this issue then? My best bet right now is a flag like `--enable-edge-tls-termination`. What would you suggest?

**Comment by arekkas** [comment]
I believe that right now the only piece of code that would be affected by this issue is [the consent challenge](https://github.com/ory-am/hydra/blob/24d34b312ee95f82def54d9f6a48e1cf3f5e3902/oauth2/handler.go#L106-L114)

**Comment by ibotty** [comment]
I prefer an option like "--edge-tls-termination-from" where you can specify one or more netmasks from which you trust the headers.

But I am fine with any way that makes it possible to use it behind a tls terminating router.

In a way, I like using RFC 7239, the FORWARDING header (confused above with PROXY), but it's not as straightforward to parse and not very widespread.

And don't you log IP addresses somewhere? That part will most likely benefit by inspecting the headers and logging the client's IP.

**Comment by arekkas** [comment]
Logging HTTP requests is usually the task of the proxy/gateway/loadbalancer. However, it should be fairly easy to add a middleware (e.g. negroni) for it. If you think this is a neccessity, please open another issue for it.

I think it's smart to let hydra detect if the original request was HTTPS or not. I checked out RFC7239 and some resources online, it looks like `X-Forwarded-Proto` is a de-facto standard. So why not use it!

Additionally, I like the idea to whitelist tls termination origins: `--edge-tls-termination-from=[127.0.0.0/16, ...]`

**Comment by arekkas** [comment]
@ibotty what do you think of the following:

```go
hostCmd.Flags().StringSlice("allow-tls-termination-from", []string{}, "Whitelist one or multiple CIDR address ranges and allow them to terminate TLS connections. Be aware that the `X-Forwarded-Proto` header must be set and must never be modifiable by anyone but your proxy / gateway / load balancer.")
```

do you have an idea how to describe this better in fewer words?

**Comment by ibotty** [comment]
I like it. I can't think of anything shorter which is as precise.

**Comment by arekkas** [comment]
Instead, this is an env var! Makes more sense for production environments IMHO

**Comment by arekkas** [comment]
```
- HTTPS_ALLOW_TERMINATION_FROM: Whitelist one or multiple CIDR address ranges and allow them to terminate TLS connections.
	Be aware that the X-Forwarded-Proto header must be set and must never be modifiable by anyone but
	your proxy / gateway / load balancer.
	Example: HTTPS_ALLOW_TERMINATION_FROM=["127.0.0.1/16","192.168.178.0/16"]
```

**Comment by arekkas** [comment]
https://github.com/ory-am/hydra/pull/165/commits/53b2f830436f8c1b2fcd43e1dec4abdc8de17b36

**Comment by ibotty** [comment]
I hope it is parsed as a comma-separated list, without the brackets. If so, the example should read

     Example: HTTPS_ALLOW_TERMINATION_FROM=127.0.0.1/16,192.168.178.0/16

btw: what about ipv6?

**Comment by arekkas** [comment]
> hope it is parsed as a comma-separated list, without the brackets. If so, the example should read

done

> btw: what about ipv6?

will be included. do you know if there's something i need to take care of when using go and ipv6?

**Comment by ibotty** [comment]
Sorry, I don't know anything about go and IPv6.
