### ISSUE TITLE
managing client definitions

### ISSUE THREAD

**Issue by boyvinall** [ory-am/hydra#197]
As per gitter chat, I've created some simple guidelines on managing client definitions with Vault.  I've stuck a few other thoughts in there too. Wasn't quite sure whether this should go into the main hydra repo or perhaps into gitbooks - so currently I've dropped this into a gist:

https://gist.github.com/boyvinall/d6e80a801fc8a7771694c2d6fde4eb4f

@arekkas Let me know where you want this, and I'll create a PR somewhere. Probably easier to manage any comments you have as part of the PR.

**Comment by arekkas** [comment]
nice! I'm trying to figure out how to do docs with hydra. I think gitbook was the wrong decision to go with because you, for example, can't create a PR there. maybe create a `doc` directory? What do you think?

**Comment by boyvinall** [comment]
Yeah, a docs directory can often work well. I'll create something with that.

**Comment by arekkas** [comment]
hey @boyvinall the [docs are now merged](https://github.com/ory-am/hydra/tree/99ac89676d4fc25650d8aae07a539dcd6f511341/docs) directly into github. if you want, you can add an FAQ entry for this.
