### ISSUE TITLE
warden: IntrospectToken always throws an error on Hydra logs

### ISSUE THREAD

**Issue by faxal** [ory-am/hydra#199]
I did some digging and it seems following lines are dead code that need to be removed. 

https://github.com/ory-am/hydra/blob/0baa04ebbbc62446b21824ecda7490864642ce68/warden/warden_http.go#L63-L66

Either that or it needs to be `application/x-www-form-urlencoded` with "token" because the other side is expecting that. Now there is a second request with an empty token which triggers the error.

**Comment by arekkas** [comment]
This looks like a bug, not sure why tests aren't catching that. I'll dig into it.

**Comment by arekkas** [comment]
still not sure why tests didn't catch it but it should work now

**Comment by arekkas** [comment]
ah, the code was actually written in a way that it didn't throw an error...copy and paste errors, as usual
