### ISSUE TITLE
AccessTokens get overridden during startup of hydra

### ISSUE THREAD

**Issue by faxal** [ory-am/hydra#207]
I was having premature token expiration issue on hydra and it was happening after I restart the hydra. 

Upon further inspection I discovered that it's due to the way `coldStart` is handled. 

Specifically this line:
https://github.com/ory-am/hydra/blob/0baa04ebbbc62446b21824ecda7490864642ce68/internal/fosite_store_rethinkdb.go#L279

It stores the same reference over and over. It works if I assign to a temp variable first.

**Comment by arekkas** [comment]
damn, this issue again (sometimes go can be a ***). thanks for digging, I'll fix it asap.
