### ISSUE TITLE
figure out a process to autobuild releases

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#210]
...because it's really annoying to do this manually.

**Comment by janekolszak** [comment]
You could create a separate tag or a branch for releases and maybe use this https://docs.travis-ci.com/user/deployment/releases ?

**Comment by arekkas** [comment]
Yes, very nice, it seems to be working with [Conditional Releases](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A).
