### ISSUE TITLE
error bad request when running tutorial

### ISSUE THREAD

**Issue by silverjam** [ory-am/hydra#211]
Running the tutorial with docker computer (and `docker exec -i -t hydra_hydra_1 /bin/bash` to run the CLI)-- I get an error from the react-idp web UI `Could not retrieve access token: Error: Bad Request`.  In the log I see:

```
hydra_1      | time="2016-08-18T09:54:31Z" level=info msg="started handling request" method=POST remote="172.18.0.4:53604" request="/oauth2/token" 
hydra_1      | time="2016-08-18T09:54:31Z" level=info msg="An error occured" error= stack=[flow_client.go:29 access_request_handler.go:74 handler.go:77 handler.go:39 router.go:299 negroni.go:41 negroni.go:24 negroni.go:33 negroni.go:33 server.go:1618 handler.go:118 handler.go:41 negroni.go:24 negroni.go:33 negroni.go:33 middleware.go:135 negroni.go:33 negroni.go:73 server.go:2081 server.go:1472 asm_amd64.s:1998] 
hydra_1      | time="2016-08-18T09:54:31Z" level=info msg="completed handling request" measure#web.latency=116204160 method=POST remote="172.18.0.4:53604" request="/oauth2/token" status=400 text_status="Bad Request" took=116.20416ms 
consent_1    | { error: 'Could not retrieve access token: Error: Bad Request' }
```

Am I doing something wrong?  Thanks!

**Comment by arekkas** [comment]
[this tutorial](https://ory-am.gitbooks.io/hydra/content/demo.html)?

**Comment by silverjam** [comment]
yes

**Comment by arekkas** [comment]
i can reproduce this, thanks for reporting

**Comment by arekkas** [comment]
https://github.com/ory-am/hydra-idp-react/commit/b290b1415538e64be999756cb4f8745c3bd220b7 should fix this, might take a minute or two until docker images are published etc etc.

**Comment by arekkas** [comment]
https://hub.docker.com/r/oryam/hydra-idp-react/builds/bxo7r3as6hys6np4k3rvbuf/

**Comment by arekkas** [comment]
it should work now, please do this:

```
# kill compose process if still running
$ docker pull oryam/hydra-idp-react # make sure the image actually updates, it should read something like "Status: Downloaded newer image for oryam/hydra-idp-react:latest"
$ docker-compose up

... re-run the tutorial
```

**Comment by arekkas** [comment]
when running the CLI from within the docker image, it looks like the callback isn't functioning because docker isn't exposing the 4445 port. if it doesn't work that way, you should try running the cli outside of docker. if you can't compile go on your system, let me know and I'll publish the binary packages

**Comment by arekkas** [comment]
however, after success you should see something like this in your browser bar:

```
http://localhost:4445/callback?code=HjLPph77FuC9If0iFwpsRjoYJdWSEcMG2K8YL-AaMD4.QrScM1twQP_MJj3FrNacsq8AzacQGPe5Ty3yHWspXsA&scope=hydra+offline+openid&state=cwjuzlwgufsweegpfquvvrbu
```

**Comment by silverjam** [comment]
Awesome, thanks, I'll give it a try in a few hours.

**Comment by arekkas** [comment]
ok, feel free to reopen if issues persist

**Comment by silverjam** [comment]
I purged purged the docker containers (and removed the shared volume) but I'm not able to verify, but also not sure how to check what version of oryam/hydra-idp-react I have either.

**Comment by arekkas** [comment]
no need to purge, this is enough: https://github.com/ory-am/hydra/issues/211#issuecomment-240687074

**Comment by arekkas** [comment]
@silverjam did you manage to get it working? if not, join the gitter channel and i'll try to help you the best i can.

**Comment by arekkas** [comment]
@silverjam i pushed a change that will expose the 4445 port in the docker image and let you do the flow with hydra running inside of docker as you wanted it to. It will be released as 0.4.1

#212

**Comment by silverjam** [comment]
@arekkas I'll look into verifying that the image I have is updated tonight (I'm at UTC-08:00)-- "docker for mac" crashed my machine then refused to start, so I ended up having to rebuild everything, thus... I'm not sure what I have at the moment.

**Comment by arekkas** [comment]
oh wow, that has never happend to me. the image should be fine, you can verify it with:

```
$ docker images oryam/hydra-idp-react
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
oryam/hydra-idp-react   latest              10a2253a9c57        7 hours ago         817.7 MB
oryam/hydra-idp-react   <none>              c02f16b85e55        11 weeks ago        825 MB

```

**Comment by silverjam** [comment]
Works now, thanks! 👍
