### ISSUE TITLE
core: (health) monitoring endpoint

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#216]
There should be a monitoring endpoint giving data on database connectivity, current state of memory and information on error rate

**Comment by waynerobinson** [comment]
Would be especially useful to control delivery by load-balancers like https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/ as well as providing some extra levers for doing things like clearing caches, etc.

**Comment by arekkas** [comment]
Yup, it would be great if there where some libraries for that. I have to check if anything exists in the go ecosystem that solves this easily.

**Comment by janekolszak** [comment]
Consul has a go library and many kinds of health checks:
https://www.consul.io/docs/agent/checks.html#TTL

**Comment by arekkas** [comment]
a very simple check (returns 204 on success) will be available at `http://hydra/health` with #293
