### ISSUE TITLE
Add version option to Hydra's CLI

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#218]
Please add version option to the hydra cli. Something like:
```
$ hydra --version
Hydra 0.4.1
```

**Comment by arekkas** [comment]
This is a good point. The issue I have right now is that we don't have an installer and we can only version the binary, not the code (without hassle). Do you have any recommendations for distributing or even automating the build process / installer?

**Comment by arekkas** [comment]
This issue is related to #210
