### ISSUE TITLE
Typo in the apiary documentation

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#220]
Documentation http://docs.hdyra.apiary.io/#reference/oauth2/manage-the-oauth2-client-collection says hydra expects *scopes* field but it expects *scope* .

Fix documentation or rename the field, thanks.

**Comment by arekkas** [comment]
thank you, this is now updated

**Comment by amerdidit** [comment]
It still says hdyra for me. 

hydra.apiary.io is private and unaccessable to me.

**Comment by arekkas** [comment]
@amerdidit I can't reproduce that. It's not private here. Probably because you went to `hydra.apiary.io` isntead of `docs.hdyra.apiary.io`
