### ISSUE TITLE
hydra clients import doesn't print client's secret

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#221]
`hydra clients import test.json` doesn't print client's secret as stated in the documentation.

http://docs.hdyra.apiary.io/#reference/oauth2/manage-the-oauth2-client-collection/create-a-new-oauth2-client

**Comment by arekkas** [comment]
@janekolszak did you provide a secret for the clients in the JSON file?

**Comment by janekolszak** [comment]
no, I have not. Setting "client_secret" will do the trick?

**Comment by arekkas** [comment]
It will set a client secret of your choosing but won't display generated ones.

**Comment by janekolszak** [comment]
Then documentation needs fixing: http://docs.hdyra.apiary.io/#reference/oauth2/manage-the-oauth2-client-collection/create-a-new-oauth2-client

**Comment by arekkas** [comment]
Resolving this issue is adding the client secret to be printed here: https://github.com/ory-am/hydra/blob/master/cmd/cli/handler_client.go#L49

**Comment by arekkas** [comment]
Thank you for pointing me at the apiary docs. The client secret should now be documented properly :)
