### ISSUE TITLE
oidc: support kid hint in header

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#222]
> I'm trying to use https://github.com/IdentityModel/oidc-client-js with Hydra. It seems to work when I use response_type=token, but fails when I add id_token. It says "No kid found in id_token" (I checked, there's no kid).

Reported by @janekolszak

**Comment by janekolszak** [comment]
I think this log contains the bad response
```
time="2016-08-20T10:40:17Z" level=info msg="completed handling request" measure#web.latency=186782098 method=GET remote=172.23.0.1 request="/oauth2/auth?client_id=wta-site&redirect_uri=https%3A%2F%2Flocalhost%2Ftestoidc%2F&response_type=id_token%20token&scope=openid%20all&state=995787dc2625419387b4ffd90d0bdab7&nonce=a96fca455a4644eaadd2847f7e2d84d6&consent=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ3dGEtc2l0ZSIsImV4cCI6MTQ3MTY4OTkxNywiaWF0IjoxNDcxNjg5NjE3LCJzY3AiOlsib3BlbmlkIiwiYWxsIl0sInN1YiI6IjY2ZWM5Njc5LWNmZDgtNDI0My05ZmEyLTQ4ZTVjOTI5YzFjMiJ9.QT38PSu0PU5i1qoQtXWAU3Y8-hUMuVF1Uw-I9DCpU88pYD-ndtrIrMm4ksyeecY3JibPHizcBb6QOeFHR3g1AKGiXl76wY6LsQwW7RXxCuNom9WWXOMZD0CpSxR_nlaiqmhnxDlPG4NiyHTr415p325wGZ7S2eUkNtDaXeCDgTijPCe8fz08YliCk6NgMyL0mXHYk3gyjaYybV8ulCPtYKLUz6vsfUWkojbTKVfgJluX1Xz62c8t53_1ckzfw1YPY67wGGr1tlDJTTOucMxb1QqDc-lVR0jfC0rjqLhzQzJOsmwjGcybrHH6-TuEGAr6s_eZj-U0GTQX46eh9QN0rOEMG8Y5YkMoUgQQA8GFaTFB0ICvBCuQgYMJ9Gr8CDvOWI2pQ0jknsZlUjt4Eh6Pb4IqZzpWnNQnyBQ76E_HjIcm9fpo7iyQzslz-80n9vHdhBnunm1xkmHR0lDCfR608J7Ko5tmrhMJwUgC_MHo7PehKEif35XkNYBaRPZVFTb4t5K0UxalMt6S6uTyEsjD7uzQUDSYdnM_Mj4zcT47obCt_VCC0amr1NpY6-yPQQu05aIcnJv62FBCTLzpU85ywZHiWUE7GYNFAKll1b0GJX1pB8HCRrFgQueSlKDmjik31oeM7dvw_fHj6DhArDFUMQgRYSk6tpfGg_DLSTyKQOo" status=302 text_status=Found took=186.782098ms 
```

**Comment by janekolszak** [comment]
Decoded with https://jwt.io/
```json
{
  "alg": "RS256",
  "typ": "JWT"
}
{
  "aud": "wta-site",
  "exp": 1471689917,
  "iat": 1471689617,
  "scp": [
    "openid",
    "all"
  ],
  "sub": "66ec9679-cfd8-4243-9fa2-48e5c929c1c2"
}
```

and signature isn't valid

**Comment by arekkas** [comment]
Ok there seems to be some strange things going on. Usually, the nonce should be included in the ID Token (the nonce can replace the kid) plus it's really weird that the signature isn't valid. Did you use the PEM encoded key from hydra for signing id tokens?

**Comment by arekkas** [comment]
What you're showing in https://github.com/ory-am/hydra/issues/222#issuecomment-241192838 is not the id token, it's the consent token issued by your idp. I'm a bit confused :|

This is what an ID token looks like, if I request it using the demo:

```
{
  "alg": "RS256",
  "typ": "JWT"
}
{
  "aud": "d7f2ee09-8d28-4be2-bb89-ce3a5e7c3217",
  "auth_time": 1471691398,
  "exp": 1471694997,
  "iat": 1471691398,
  "iss": "hydra.localhost",
  "nonce": "wqwdpdahrbeotxwzqaldhyow",
  "sub": "john.doe@me.com"
}
```

**Comment by arekkas** [comment]
Plus, according to spec, the `kid` claim does not exist in the id token, please check: http://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by janekolszak** [comment]
Sorry for that. I can't find what's the id_token returned by hydra.

The id_token validation fails here:
https://github.com/IdentityModel/oidc-client-js/blob/178d19f279bfeb39915db9fc443623605130da33/src/ResponseValidator.js#L246

**Comment by arekkas** [comment]
> Sorry for that. I can't find what's the id_token returned by hydra.

Why not?

> The id_token validation fails here:
https://github.com/IdentityModel/oidc-client-js/blob/178d19f279bfeb39915db9fc443623605130da33/src/ResponseValidator.js#L246

I can't find `kid` neither in the claims nor in the header to be mandatory. It looks like the library is faulty.

**Comment by arekkas** [comment]
You should be able to request an ID token with an request like this:

```
https://localhost:4444/oauth2/auth
?client_id=d7f2ee09-8d28-4be2-bb89-ce3a5e7c3217
&redirect_uri=http%3A%2F%2Flocalhost%3A4445%2Fcallback
&response_type=code <- alternatively, `token+id_token`
&scope=hydra+offline+openid <- openid is required
&state=uksnidtqqzrrvfgqaqciaxac
&nonce=rzowrioghmymcrhfapakgfaa
```

When using `hydra token user`, the id token will be shown in the console only, not the browser.

**Comment by arekkas** [comment]
The ID Token issued by the [OpenID Connect Playground](https://openidconnect.net/) doesn't include a `kid` either.

**Comment by arekkas** [comment]
According to http://openid.net/specs/openid-connect-core-1_0.html#Signing a `kid` may be included if multiple JSON Web Keys are in the JWK Set which was used to sign the key. This is usually required when key rotation is used to identify which key was responsible for signing and reduce computational overhead.

From my point of view, it would be ok to include the `kid` hint in the header field, even if it's not mandatory. What do you think?

**Comment by janekolszak** [comment]
If other OIDC providers do this it would be nice to have as well.

**Comment by arekkas** [comment]
One issue I have with this, is that it's not possible to identify the JSON Web Key Set, as it doesn't have an ID in the spec. In Hydra however, it is much more important what the set id is than what the key id is, as the API is called with, e.g. `https://hydra/jwks/hydra.openid.connect`. The set only contains kid `public` and `private`.

This in turn would mean, that the `kid` value in the id token header would always simply be `private`. Including the complete path (`hydra.openid.connect/private`) however would break the original spec and make this probably incompatible with existing libraries.

This is probably best explained in an example from the real code:

```go
// OpenIDConnectKeyName = "hydra.openid.connect"
keys, err := km.GetKey(oauth2.OpenIDConnectKeyName, "private")
```

This is a tricky one, maybe I have to overthink JWK kid naming and, for example, prefix the JSON Web Key Set ID: `"kid": "hydra.openid.connect/private"`

**Comment by janekolszak** [comment]
What about key rotation? Hydra manages that any way?

**Comment by arekkas** [comment]
#73

**Comment by janekolszak** [comment]
https://github.com/IdentityModel/oidc-client-js/issues/96

**Comment by arekkas** [comment]
I'm closing this because I feel confident that it's not Hydra's fault :)
