### ISSUE TITLE
Vendor: Upgrade to jwt-go 3.0.0

### ISSUE THREAD

**Issue by leetal** [ory-am/hydra#229]
This is essentially the same that have been done at fosite [issue 76](https://github.com/ory-am/fosite/issues/76). 

Basically the new version of jwt-go have better support for claims, and right now hydra won't build when using the head of fosite due to versioning clashes. 

I will start fixing this tomorrow and supply a PR tomorrow evening.

**Comment by leetal** [comment]
@arekkas I think i have successfully updated jwt-go in hydra now as well to 3.0.0. All tests in the oauth2 package pass. BUT, the following commit [7faee6bb @ fosite](https://github.com/ory-am/fosite/commit/7faee6bbd53ee762ddfe194fb2ea5e7d0205e46d) really messes up the tests in hydra/warden. Thus, i cannot verify the changes i've made and i really think you should take a look at what that commit does to hydra.

**Comment by arekkas** [comment]
ok, will do, thanks for the effort so far

**Comment by arekkas** [comment]
yeah that commit is faulty

**Comment by leetal** [comment]
I think it actually accepts more or less all scopes right now...

**Comment by arekkas** [comment]
no i think it works fine, the test cases seem ok:

```go
	scopes = []string{"hydra", "openid", "offline"}
	assert.False(t, strategy(scopes, "foo.bar"))
	assert.False(t, strategy(scopes, "foo"))
	assert.True(t, strategy(scopes, "hydra"))
	assert.True(t, strategy(scopes, "hydra.bar"))
	assert.True(t, strategy(scopes, "openid"))
	assert.True(t, strategy(scopes, "openid.baz.bar"))
	assert.True(t, strategy(scopes, "offline"))
	assert.True(t, strategy(scopes, "offline.baz.bar.baz"))
```

**Comment by arekkas** [comment]
could you open a PR with your changes so i know which branch to look at?

**Comment by leetal** [comment]
On its way! Keep in mind that tests might/will fail. I cannot guarantee anything ;)

**Comment by arekkas** [comment]
that's ok

**Comment by arekkas** [comment]
resolved

**Comment by faxal** [comment]
@arekkas @leetal I was a in a hurry with this commit: https://github.com/ory-am/fosite/commit/7faee6bbd53ee762ddfe194fb2ea5e7d0205e46d

I realized after I pushed that it can be simplified to this:

```
if current != needle {
    break
}
```

**Comment by arekkas** [comment]
Ah yes, if you want, create a PR
