### ISSUE TITLE
oauth2: token revocation endpoint

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#233]

**Comment by waynerobinson** [comment]
Is this to explicitly revoke tokens (e.g. by logging out)? Is there currently a revocation list for access tokens in Hydra somewhere that works with the Warden and OAuth Identity endpoints?

**Comment by arekkas** [comment]
Yes, exactly, this endpoint is for revoking valid tokens. There is currently no possibility to revoke tokens.

**Comment by arekkas** [comment]
done!

**Comment by waynerobinson** [comment]
Does refreshing a token revoke the previous one? This is how other providers I've used work, but unsure as to whether that's the standard.

**Comment by arekkas** [comment]
Per spec: the refresh token revokes all future refresh tokens and all access tokens issued by the refresh token. The revokation of an access token revokes all refresh tokens, given any.
