### ISSUE TITLE
consider signing up for Core Infrastructure Initiative badge

### ISSUE THREAD

**Issue by boyvinall** [ory-am/hydra#246]
Just FYI, I heard recently about https://bestpractices.coreinfrastructure.org/ and thought of you :grinning: The guy from there was talking about it on https://changelog.com/215/, sounded possibly relevant for you.  You can see the criteria at https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md

**Comment by arekkas** [comment]
awesome, thanks for the suggestion. hydra is basically doing almost everything already: https://bestpractices.coreinfrastructure.org/projects/364

**Comment by boyvinall** [comment]
Cool!  On the static analysis thing, you could maybe try https://github.com/HewlettPackard/gas - I've not used it myself on anything yet but heard it mentioned on https://changelog.com/gotime-14/

**Comment by arekkas** [comment]
nice! I will!

**Comment by arekkas** [comment]
currently blocking:

* https://github.com/HewlettPackard/gas/issues/51
* https://github.com/HewlettPackard/gas/issues/50

**Comment by arekkas** [comment]
done!
