### ISSUE TITLE
oauth2: state parameter is missing when response_type=id_token

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#254]

**Comment by janekolszak** [comment]
Confirmed. 

I can verify when it's solved.

**Comment by arekkas** [comment]
upstream https://github.com/ory-am/fosite/issues/96

**Comment by arekkas** [comment]
resolved by https://github.com/ory-am/fosite/commit/4db14222a006bfdc1e7f2b2769e53f2dbd69f128
