### ISSUE TITLE
Bad HTML encoding of the scope parameter

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#259]
Hi
There seems to be a bug in passing the **scope** param in the `id_token token` response. 
I requested `openid all` scopes and the respoinse url had `openid%252Ball`.

So you're html encoding the + sign. I think you should be html encoding only the names of the scopes (if any encoding is needed at all)

**Comment by arekkas** [comment]
Thanks for reporting

**Comment by arekkas** [comment]
upstream https://github.com/ory-am/fosite/issues/95

**Comment by arekkas** [comment]
resolved in https://github.com/ory-am/fosite/commit/ddd8d035eb081200eff2ae9c4235c7228ec0b0b6
