### ISSUE TITLE
When invalid/expired token is used for /warden/allowed endpoint, status 500 is returned

### ISSUE THREAD

**Issue by subandroid** [ory-am/hydra#262]
I think in this case, we should raise HTTP 401 (Unauthorized). So that client can attempt to obtain new token.

**Comment by arekkas** [comment]
to be resolved in https://github.com/ory-am/fosite/pull/98

**Comment by matteosuppo** [comment]
Uhm, it's happening again. Seems like the error returned doesn't implement StatusCodeCarrier so it return 500
