### ISSUE TITLE
connections: remove connections API

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#265]
I think the social connections API is adding confusion around what hydra is doing and what not. Additionally, I don't think anyone really uses it.

vote :+1: to remove or :-1: to keep

**Comment by arekkas** [comment]
vote :+1: or :-1:

**Comment by janekolszak** [comment]
This API is a mapping between local userid and remote userid. 

This mapping would be used in the IdP, keeping this in hydra is just one request more for IdP.
