### ISSUE TITLE
support for ldap for user storage

### ISSUE THREAD

**Issue by allan-simon** [ory-am/hydra#28]
I don't know how to handle that in a nice and microservice way (have hydra to connect to 3rd-party user provider, that all must fullfil a http api contract, so that any body can implement his user provider and it will connect nicely with hydra, without needing to have that in hydra itself ?)

But as this tool is aim for corporate scenario, and a lot of company do store their user in LDAP, hence being able to get the user from there would IMHO greatly the places where hydra would be relavant.

**Comment by arekkas** [comment]
Hey thanks for your feedback, I think integrations like LDAP, OpenID and SAML/JWT Assertions are important for the project's success. I have not a clear roadmap yet when to get there but I'm happy for any input, ideas or contributions regarding that matter.

**Comment by arekkas** [comment]
You could easily implement LDAP for user storage by introducing a new connector (they are still called providers). The interface can be found [here](https://github.com/ory-am/hydra/blob/master/oauth/provider/provider.go) with an example implementation [here](https://github.com/ory-am/hydra/blob/master/oauth/provider/dropbox/dropbox.go). Please be aware that the Provider interface is not final and is subject to change to make things more compatible with non-OAuth2 providers. Additionally, Providers will be renamed to Connectors which is tracked in #38

**Comment by allan-simon** [comment]
thanks for the hint, I think I will have time to look on it in 4~5 weeks, I will tell you if I start to write actual code so that tobe sure things integrate nicely :)

**Comment by arekkas** [comment]
:+1: :)

**Comment by arekkas** [comment]
with #62 hydra has a new identity workflow. you can now implement LDAP easily
