### ISSUE TITLE
docs/apiary: add at_ext note to warden endpoints

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#287]

**Comment by arekkas** [comment]
also, it's not clear that token introspection requires an access token, not basic authorization

**Comment by waynerobinson** [comment]
Also see #289 regarding the actual required authentication mechanism for this endpoint being different from our discussion earlier today.

And #290 regarding id_ext only ever being included in the OpenID token and never when requesting data again from Hydra.

**Comment by arekkas** [comment]
done (y)
