### ISSUE TITLE
support SAML in addition to OAuth2

### ISSUE THREAD

**Issue by allan-simon** [ory-am/hydra#29]
In addition to OAuth2, the SAML protocol would be great to have, to support legacy application that doesn't speak OAuth2 (and god knows there's a lot in  corporate world)

spoiler: in my company (of several hundreds employees)  OAuth2/SAML  and LDAP/MySQL are the two things we're using for authentication, and having these would cover nearly all our use cases

**Comment by arekkas** [comment]
SAML support would be great. There's already a TODO item for this in the oauth2 handler: https://github.com/ory-am/hydra/blob/master/oauth/handler/handler.go#L263-L268

**Comment by allan-simon** [comment]
thanks, after on a side note, just my humble advice, but i always associate my TODO in the code with a ticket in github (by doing `TODO: #4 blabla` , so that people that come around like me, are more likely to read the issues list rather than the code :) and if somebody is to give you a hand they can directly check the list and grep for the issue number

**Comment by arekkas** [comment]
Thanks, great idea! :)

**Comment by allan-simon** [comment]
you're welcome, I'm really looking forward to see your project becoming more mature :)

**Comment by arekkas** [comment]
This is now possible by implementing a consent endpoint that understands SAML :)
