### ISSUE TITLE
github: comply with Go license terms

### ISSUE THREAD

**Issue by mappu** [ory-am/hydra#300]
Hi,

At the time of writing, the repository tagline on Github is

> A secure, reliable, fast and lightweight OAuth2, OpenID Connect and Access Control provider that runs on top of any existing authentication infrastructure. Written in **Google** Go. https://www.ory.am/products/hydra

It's against [the Go license](https://golang.org/LICENSE) to use Google's name to promote your project:

> Neither the name of Google Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

I think you should rephrase it simply as "Written in Go".

I would make a PR but this property of the repo is not stored in Git.

Thanks
mappu

**Comment by arekkas** [comment]
Thanks for noticing! What do you think a good substitute would be? "Written in Go (Golang)"?

**Comment by arekkas** [comment]
I removed it from the repository description. Did you find that phrase anywhere else?

**Comment by arekkas** [comment]
resolved :)
