### ISSUE TITLE
Production Daemon Running/Logging

### ISSUE THREAD

**Issue by waynerobinson** [ory-am/hydra#302]
How would you recommend setting up Hydra to execute (in the background) and log in production?

**Comment by arekkas** [comment]
I think the easiest way is to run it on top of a PaaS, such as kubernetes or docker swarm. You get logging, health checking and restarting the service for free. Is that an option?

**Comment by waynerobinson** [comment]
Doesn't quite work for us at the moment, but we'll make do.
