### ISSUE TITLE
core: Redis backend

### ISSUE THREAD

**Issue by 115100** [ory-am/hydra#306]
I've started some work on this on my own [branch](https://github.com/115100/hydra/tree/redis-client).

From what I can see, ladon also requires Redis changes and it seems someone else is working on it here https://github.com/ory-am/ladon/issues/38.

**Comment by arekkas** [comment]
Awesome, feel free to create a PR any time! There hasn't been any activity on https://github.com/ory-am/ladon/issues/38 so you would probably have to implement a store for that too
