### ISSUE TITLE
oauth2/revocation: token revocation fails silently with sql store

### ISSUE THREAD

**Issue by cainjonm** [ory-am/hydra#311]
Using `postgresql` as the backing database.

It appears that if no session is passed through to `findSessionBySignature`[[1]](https://github.com/ory-am/hydra/blob/master/oauth2/fosite_store_sql.go#L147) causes ToRequest[[2]](https://github.com/ory-am/hydra/blob/master/oauth2/fosite_store_sql.go#L91) to return 'No session defined'.

It looks like `fosite/handler/oauth2/revocation.go` `RevokeToken[[3]](https://github.com/ory-am/fosite/blob/master/handler/oauth2/revocation.go#L21) explicitly doesn't pass a session in causing, Line 41 of this file to return an error before any revocation occurs.

The error is then 'ignored' at [[4]](https://github.com/ory-am/fosite/blob/master/revoke_handler.go#L101). On this, i read the comment, but i'm not sure ignoring revocation errors is the best approach, since as a consumer you would expect on a 200 that the revocation has definitely occurred.

**Comment by arekkas** [comment]
Awesome analysis, thank you so much. This will help me a lot in debugging!

**Comment by arekkas** [comment]
ps: And it sounds very reasonable, we had issues with sessions in the past

**Comment by arekkas** [comment]
Awesome analysis, thank you @cainjonm

**Comment by arekkas** [comment]
#312
