### ISSUE TITLE
oauth2: aud parameter does not allow arrays

### ISSUE THREAD

**Issue by 115100** [ory-am/hydra#314]
I'm using `go-jose` library to marshal my claim into JSON. The [jwt.Audience](https://github.com/square/go-jose/blob/v2.0.1/jwt/claims.go#L78) type unmarshals/marshals into a string slice/array by default.

Hydra's consent validation I assume makes a check assuming a string:

`ERRO[0413] An error occurred                             error=Audience mismatch`

According to the RFC, single values can still be in an array though:

```
In the general case, the "aud" value is an array of case-
sensitive strings, each containing a StringOrURI value.  In the
special case when the JWT has one audience, the "aud" value MAY be a
single case-sensitive string containing a StringOrURI value.
```

When I force the consent audience to be marshalled to a string, my consent validates fine.

**Comment by 115100** [comment]
Looks like it's a fosite thing. I can open a PR and enforce a slice size of 1?

**Comment by arekkas** [comment]
I think both are valid (array and string) although array certainly leaves more options. Do you have a specific use case why this should work with Hydra? Because I don't think there is a way to have multiple audiences in hydra at the moment (it's always the client_id)

**Comment by 115100** [comment]
Sorry, I wasn't very clear. I don't expect there to be more than one audience ever.

`fosite/token/jwt`'s `ToString` only works with a string parameter.

`aud` may still be a single element array though, in which case I won't be authorised after a callback from the consent server.

**Comment by 115100** [comment]
An example fix would be this in ToString:

```
+       if sl, ok := i.([]string); ok {
+               if len(sl) == 1 {
+                       return sl[0]
+               }
+       }
+
```

**Comment by arekkas** [comment]
ah I see, that makes sense!
