### ISSUE TITLE
oidc: SCIM compliance

### ISSUE THREAD

**Issue by jainh** [ory-am/hydra#320]
Hi,
 Does OpenID Connect implementation support the following draft  [Draft](http://openid.net/specs/openid-connect-scim-profile-1_0.html) ?
 Also, how to integrate SCIM within the hydra and harmonize it with existing OpenID connect?

**Comment by arekkas** [comment]
No SCIM is not supported. What is dex?

**Comment by jainh** [comment]
@arekkas Typo corrected, is it possible to create proposal and priority for SCIM support through Hydra ?

**Comment by arekkas** [comment]
@jainh I'm so sorry, but I don't understand what you are saying

**Comment by jainh** [comment]
@arekkas "dex" i put was typo corrected it to Hydra but my question is as per draft following is what the specification define:
" Discovery metadata indicating the availability of a SCIM protocol base endpoint.
 Dynamic registration metadata that is used to indicate a clients intent to use the SCIM protocol and its associated endpoint.
 An additional ID Token claim which specifies the SCIM resource endpoint and identifier associated with the authenticate subject.
 In addition to the above metadata attributes and claims, the specification will also show how a client MAY access the SCIM endpoint."
So, is it possible OpenID connect implementation in hydra can support these attributes (scim_id, scim_location, scim_profile, scim_endpoint) ?

**Comment by arekkas** [comment]
I see, Hydra itself is currently not working with SCIM. I am unfortunately very unfamiliar with SCIM itself and would have to study it first before I can give an answer if it is realistic that Hydra will support SCIM and if so, how that support would look like. The [OpenID Connect Profile for SCIM Services](http://openid.net/specs/openid-connect-scim-profile-1_0.html) draft is very young and quite sparse in description. For example, it's not clear to me where the metadata will be served.

I fear that I can not help you right now, and SCIM is currently not a priority.

**Comment by jainh** [comment]
@arekkas would you ok to accept help, if one need to add support for SCIM ?

**Comment by arekkas** [comment]
Sure, always open to pull requests!

**Comment by jainh** [comment]
@arekkas can you point the documentation and suggestion where to look in the code, before adding support for the SCIM?

**Comment by arekkas** [comment]
As I said I don't know how SCIM works so I can't point you to the right parts. Unfortunately, you have to figure it out yourself. Feel free to come back if you have more specific questions.

**Comment by arekkas** [comment]
Closing because we currently don't have capacities to implement SCIM compliance. Please ask on gitter if you have further questions.

**Comment by supercairos** [comment]
Is there any plans to reopen this issue since the SCIM standard has evolved to a more mature RFC ? Maybe in Kratos ?
