### ISSUE TITLE
JsonWebTokenError: jwt must be provided

### ISSUE THREAD

**Issue by stelioschar** [ory-am/hydra#321]
While running `docker-compose up` I follow this steps:

1. http://192.168.99.100:3000/
2. Login with john.doe@me.com: foobar
3. Error 500 in http://192.168.99.100:3000/api/login
`{"error":"Could not verify consent challenge: JsonWebTokenError: jwt must be provided"}`

Is there a workaround to make it work?

**Comment by arekkas** [comment]
Please, read the manual. It is explained how the docker-compose tutorial works.

https://ory-am.gitbooks.io/hydra/content/tutorial.html
