### ISSUE TITLE
Why hydra github homepage crash when I visit ( while scrolling down)

### ISSUE THREAD

**Issue by chinglinwen** [ory-am/hydra#323]
I think every time I visit hydra github homepage, while scrolling down a half page,  the tab is crash, even my browser and whole system becomes no response ( I do wait for a long time(5 minutes) to recover ) ( I have experience that I have to restart my computer to recover )

I'm sure it happen many times. I don't know why hydra is special, Others github repositories are fine

Is that hydra have special contents?

os: windows7
chrome:Version 54.0.2840.71 m (64-bit)

**Comment by arekkas** [comment]
Unofrtunately, I can't reproduce this issue with the same chrome version. We are only using standard markdown in the readme (try opening it on it's own [here](https://github.com/ory-am/hydra/blob/master/README.md)). What usually helps is setting up a new chrome profile or cleaning cookies/cache. If nothing helps, please contact GitHub support

**Comment by chinglinwen** [comment]
> (try opening it on it's own here).

The provided link is okay, no problem,  I tried open the that homepage in incognito is okay too
This time I tried open the hydra github homepage again, it is okay, no problem ( even though I don't know why )

Sorry if I report the issue at wrong place ) ( by the way, I send the feedbacks to the chrome too, before I create the issue here )

**Comment by chinglinwen** [comment]
While I doing check the chrome version, I guess I just got an updated version ( when I doing verify above), So the problem may fixed by the new chrome version (Version 55.0.2883.87 m (64-bit))
