### ISSUE TITLE
oauth2: does Hydra support LDAP?

### ISSUE THREAD

**Issue by jainh** [ory-am/hydra#325]
Hi,
I have following questions
1) Does Hydra support LDAP with OpenID connect ?
2) Token validation as a service ?

**Comment by arekkas** [comment]
Please read the docs and get familiar with Hydra. Hydra does not solve authentication, thus LDAP is not supported in Hydra. However, you can easily integrate LDAP in your authentication app.

> Token validation as a service ?

I'm not sure what you're asking here.

Also, please chose appropriate issue titles.

**Comment by arekkas** [comment]
closing as the question has been answered and response is pending
