### ISSUE TITLE
sql: deleting policies does not delete associated records with mysql driver

### ISSUE THREAD

**Issue by johnwu96822** [ory-am/hydra#326]
In MySQL there are four tables for ladon policies. When deleting a policy, it is only deleted from "ladon_policy" table, but the data for this policy in three other ladon_policy_* tables are not removed.

**Comment by johnwu96822** [comment]
This happens on MySQL

**Comment by arekkas** [comment]
@johnwu96822 is this a critical issue for you?

**Comment by johnwu96822** [comment]
@arekkas Yes we have deployed Hydra for testing. If this issue doesn't get fixed and we modify policies (Hydra currently modifies a policy by **deleting** and recreating it), we'll get a bunch of policy records in those tables and we wouldn't know which record we'd get.

**Comment by arekkas** [comment]
see https://github.com/ory-am/hydra/pull/329/commits/070520d3d862e39ce1a199be7f50f95380ad7e1e

**Comment by arekkas** [comment]
resolved by #329
