### ISSUE TITLE
Apparent failure on load with ECDSA key

### ISSUE THREAD

**Issue by NightDevel** [ory-am/hydra#328]
hydra host --https-tls-cert-path=private-test.pem --https-tls-key-path=key-test.pem
INFO[0000] DATABASE_URL not set, connecting to ephermal in-memory database.
WARN[0000] Expected system secret to be at least 32 characters long, got 0 characters.
INFO[0000] Generating a random system secret...
INFO[0000] Generated system secret: EIwYn4FFcVCfe<EPylQhWP<=WMQg<&U5
WARN[0000] WARNING: DO NOT generate system secrets in production. The secret will be leaked to the logs.
INFO[0000] Key pair for signing hydra.openid.id-token is missing. Creating new one.
INFO[0002] Key pair for signing hydra.consent.response is missing. Creating new one.
INFO[0006] Key pair for signing hydra.consent.challenge is missing. Creating new one.
WARN[0009] No clients were found. Creating a temporary root client...
INFO[0009] Temporary root client created.
INFO[0009] client_id: fc4130fb-c01d-4f49-b801-8c85f8d9be47
INFO[0009] client_secret: fC3DzwS.TSr(!7n?
WARN[0009] WARNING: YOU MUST delete this client once in production, as credentials may have been leaked in your logfiles.
WARN[0009] Could not load x509 key pair: %s{[] <nil> [] [] <nil>}
WARN[0009] No TLS Key / Certificate for HTTPS found. Generating self-signed certificate.
INFO[0009] Setting up http server on :4444

Thanks.

**Comment by arekkas** [comment]
Without knowing what the keys look like I can't help you.

**Comment by NightDevel** [comment]
Nevermind, I'm an idiot and didn't read the documentation properly.  Apologies.

**Comment by arekkas** [comment]
No worries, we all make mistakes :)
