### ISSUE TITLE
[DOC]How to implement connector for LDAP with new identity workflow

### ISSUE THREAD

**Issue by flotho** [ory-am/hydra#339]
Hi,

I saw multiple issue regarding LDAP compliance etc..
I also see that since the #62 the implementation of a ldap connector should be "easier"
I'm looking for an appropriate documentation, any resources?
regards

**Comment by arekkas** [comment]
As stated in the docs, Hydra does not solve authentication itself and uses something called the consent flow to validate a user's identity. If you need LDAP, you need to implement an endpoint that is capable of performing the consent flow and that uses LDAP for authentication. You can read up on the consent flow [in the docs](https://ory-am.gitbooks.io/hydra/content/oauth2.html#overview)

**Comment by flotho** [comment]
thanks, 
A little hard to understand from now for me but I'll dign into this.
regards

**Comment by arekkas** [comment]
One image is missing in the docs (it's already fixed in a PR which isn't merged yet). It's [this one](https://github.com/ory-am/hydra/blob/master/docs/images/consent.png). Might help to clarify some things.

**Comment by arekkas** [comment]
Closing, feel free to ask on our gitter chat channel if you need help

**Comment by MelleKoning** [comment]
Apparrently gitter chat moved to discord https://discord.gg/PAMQWkr
