### ISSUE TITLE
neo4j DB support?

### ISSUE THREAD

**Issue by foobargeez** [ory-am/hydra#341]
Hello,
I am planning to use hydra and wondering if you have plans to support neo4j graph daatbase as a storage backend. We are heavy on neo4j and bringing up another DB just for this is one more thing to maintain and manage. Thanks in advance!

**Comment by arekkas** [comment]
No, Neo4j will not be supported officially. You can always try to implement your own adapters, but they have to be maintained by you.

**Comment by foobargeez** [comment]
Thanks for the response!
