### ISSUE TITLE
Problems with the authorization code flow

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#342]
Hi!
I have a problem with using `response_type=code` in javascript library (https://www.npmjs.com/package/openid-client). If I use `response_type=code id_token` then it'll fail with `Response code 401 (Unauthorized)`

#### Request:
```
https://hydra/oauth2/auth?redirect_uri=wta%3A%2F%2Fauth&scope=openid%20all&state=6a0cdc50-3192-4826-9172-d0536ac1fc2d&nonce=d20f5a65-7594-433c-adc5-80cc784bfffa&response_type=code&client_id=wta-d
```

#### Response:
```
wta://auth?error=invalid_request&error_description=The+request+is+missing+a+required+parameter%2C+includes+an+invalid+parameter+value%2C+includes+a+parameter+more+than+once%2C+or+is+otherwise+malformed&state=6a0cdc50-3192-4826-9172-d0536ac1fc2d
```

#### Client:
```json
{
  "scope": "openid all",
  "redirect_uris": [
    "wta://auth"
  ],
  "grant_types": [
    "implicit",
    "authorization_code",
    "refresh_token"
  ],
  "response_types": [
    "code",
    "token",
    "id_token"
  ]
}
```

**Comment by arekkas** [comment]
Which version of Hydra are you running? Do you think this is a regression issue of 0.7?

**Comment by arekkas** [comment]
Also @janekolszak could you include the server side logs from hydra leading up to the error? They usually give better hints at what's happening, especially with `LOG_LEVEL=debug`

**Comment by janekolszak** [comment]
This is v0.7.1.
How do I set the log level?

**Comment by arekkas** [comment]
Through env vars:

```
export LOG_LEVEL=debug
hydra host ...
```

**Comment by arekkas** [comment]
Did this error occur in the 0.6 release?

**Comment by janekolszak** [comment]
I don't know, should I check?

**Comment by arekkas** [comment]
No, I'll try to reproduce it and let you know if I can't

**Comment by arekkas** [comment]
@janekolszak could you please post the output of:

```
curl --header "Authorization: bearer $(hydra token client)" http://localhost:4444/clients/wta-d
```

**Comment by arekkas** [comment]
Ok, nevermind. Apparently the redirect URL check is currently not working with custom redirect protocols at the moment!

**Comment by arekkas** [comment]
Found the issue. Fosite is checking wether the redirect URL is secure or not and returns false if not. In this case, since it's a custom protocol, it's saying: nope, that isn't secure.

See: https://github.com/ory-am/fosite/blob/master/handler/oauth2/flow_authorize_code_auth.go#L44-L46

Going to fix this with hydra 0.7.2, sorry for the inconvenience

**Comment by janekolszak** [comment]
Are you going to prepare a release?

**Comment by arekkas** [comment]
yup
