### ISSUE TITLE
sql: limit maximum open connections, document timeout options through DSN

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#359]

**Comment by waynerobinson** [comment]
Having a sensible default for `MaxIdleConnections` is a good idea.

I don't know what the definition of sensible is though, LOL. 10 idle connections? 

Being able to override with an environment variable would be even better.

Whilst you're in there with config, being able to set `MaxConnections` would be good too. Including maybe a maximum sensible default for this too (based on a reasonable expectation about concurrency … like `cores * 2` or something).

**Comment by waynerobinson** [comment]
👌
