### ISSUE TITLE
adding RethinkDB as a Store

### ISSUE THREAD

**Issue by joeblew99** [ory-am/hydra#39]
I want to use this but with rethinkdb.

Anyone have any thoughts on this ?

What i intend to do:

This looks like what needs to be ported.
https://github.com/ory-am/hydra/blob/master/account/postgres/store.go
So just a matter of making a rethinkdb folder, and then porting across store.go.

**Comment by arekkas** [comment]
Yes, all store implementations are abstracted and it should be possible to implement other store backends. I would however **absolutely** not recommend to use a No-SQL / Non-Acid solution for your auth* services.

RethinkDB, like probably all No-SQL databases, is not [ACID compliant](https://www.rethinkdb.com/faq/). Let's say you revoke a token. Without ACID compliance, the token will be revoked *some time in the future*. An attacker owning the revoked would therefore still have access although access has been revoked until RethinkDB has propagated the changes across the cluster.

It is a common misconception to use No-SQL databases for structured data, which is *most of the times* true where No-SQL is used. 

Here's my advice:
1. Use No-SQL solutions *only* if you're storing documents, not if you're storing structured data.
2. Don't use No-SQL solutions unless you absolutely know *why* you're using them and have *a very good reason* to choose No-SQL over SQL / ACID

**Comment by arekkas** [comment]
If you want to use RethinkDB anyways (e.g. no need for uber-security) there are different stores that need to be implemented for this. For example:

* https://github.com/ory-am/hydra/blob/master/account/storage.go
* https://github.com/ory-am/hydra/blob/master/oauth/provider/storage/storage.go

If you need any help implementing or if you want to try things out feel free to ask me here or on our gitter channel: https://gitter.im/ory-am/hydra?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by joeblew99** [comment]
Thanks for the feedback from: 
https://www.rethinkdb.com/docs/architecture/

.Write atomicity is supported on a per-document basis – updates to a single JSON document are guaranteed to be atomic. RethinkDB is different from other NoSQL systems in that atomic document updates aren’t limited to a small subset of possible operations – any combination of operations that can be performed on a single document is guaranteed to update the document atomically.


It maybe that this scope if atomicity is enough, but until idig through the DAL / CRUD in the code I can't say.
It all comes down to how relational your design is. If its no too much, its possible to scope everything to a su gle json dic for atomic reason.

**Comment by arekkas** [comment]
Hey yep you're absolutely right. I was a little in a hurry and did not read up on everything, sorry for that :)

Atomicity is already one step in the right direction. If you don't manage an uber RethinkDB cluster, it should be a viable solution for Hydra. Osin (the OAuth2 library behind Hydra) actually already supports a RethinkDB: https://github.com/ahmet/osin-rethinkdb

You could play around with osin and osin-rethinkdb to get things started. Once that works it shouldn't be hard to get RethinkDB working for Hydra.

**Comment by joeblew99** [comment]
It's OK.

Nice. Good idea. Will take a crack at it tomorrow.
But I need all that hydra has, so will have to bite the bullet.

Cheers

**Comment by leetal** [comment]
I'm pro for adding RethinkDB. If you haven't already started working on it, I'll take a bite at it tomorrow. We use RethinkDB in our service backend and has so far not had any problems with atomicity, like pushing changes through the clusters immediately.

**Comment by leetal** [comment]
Update on this: 40% percent done last night. Will finish after work tonight.

**Comment by arekkas** [comment]
You rock!

**Comment by joeblew99** [comment]
Hey Alexander. I never got time to do this , so thanks for this. I will be
able to help beta test for sure and contributed back I hope

**Comment by leetal** [comment]
So, i didn't finish this today, but most certainly will tomorrow. I only have one function left in ladon (TestFindPoliciesForSubject) to implement but since that function is quite harsh to overview, i'll finish this tomorrow instead so i can get some sleep tonight ;) 

@arekkas I think it's time to add rethinkdb support to dockertest as well. Right now all tests for rethinkdb are done locally instead of run in a container.

**Comment by leetal** [comment]
Ok, i think i'm done now :) Will need some live testing (how the heck i now do that?) and some smaller polishing bits, but at least hydra starts and sets upp all tables without giving any errors!! YAY!

**Comment by arekkas** [comment]
good stuff! :)

**Comment by joeblew99** [comment]
If you can push and merge I can try it out on Monday
