### ISSUE TITLE
Replace osin with ory-am/fosite

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#46]

**Comment by leetal** [comment]
:+1: on this one ;)

**Comment by arekkas** [comment]
:) I'm very busy at this and next week due to exams and some other work related things but I will start working on improving Hydra **a lot** beginning mid/end of feb :)

**Comment by leetal** [comment]
Awesome Aeneas! :D
Den 2 feb 2016 12:08 skrev "Aeneas" <notifications@github.com>:
