### ISSUE TITLE
Add Dockerfile for autobuild

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#60]
https://hub.docker.com/r/oryam/hydra/

**Comment by sbani** [comment]
My suggestions what should be done here:

## Alpine and/or debian
Create an image based on alpine `golang:1.6-alpine` and debian `golang:1.6`
### Info from the golang image
> This variant is highly recommended when final image size being as small as possible is desired. The main caveat to note is that it does use musl libc instead of glibc and friends, so certain software might run into issues depending on the depth of their libc requirements.
### Image sizes
```
$ sudo docker images -a
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
golang                 1.6                 2529f72145a7        8 days ago          744 MB
golang                 1.6-alpine          c40da134e949        4 weeks ago         238 MB
```
## All in one package
Should we create an "all in one package" with postgres? Could be useful for testing purpose like the vagrant machine is.

## Build and push
One task is to build and push the image with the CI server (travis)

## Docker compose
Create a compose yaml to run database and hydra with one command. I don't know how to "hide" the database passwords - by environments vars?

**Comment by arekkas** [comment]
Looks good! As of right now, we have multiple executables (see [cli](https://github.com/ory-am/hydra/tree/master/cli)). I was thinking of splitting those up in separate environments as this is tricky do deal with in buildpacks. Could multiple executables work with Docker or is it there an issue as well?

**Comment by arekkas** [comment]
Ok, of course we could simply build multiple executables in the Dockerfile and expose them on different ports. So it shouldn't be a huge deal

**Comment by sbani** [comment]
The [docker best practice](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run-only-one-process-per-container) doc says:
> In almost all cases, you should only run a single process in a single container.

That's why we should create multiple containers for the different executables.

**Comment by arekkas** [comment]
Ok, I don't think that would work with docker autobuild. Looks like we have to create multiple repositories.
