### ISSUE TITLE
Update GoRethink imports

### ISSUE THREAD

**Issue by dancannon** [ory-am/hydra#78]
Hey, I was having a quick look through the latest release (congratulations by the way) and noticed that you were importing GoRethink using two different imports (github.com/dancannon/gorethink and gopkg.in/dancannon/gorethink.v2). 

It would probably make sense to only use one of them, preferably gopkg.in/dancannon/gorethink.v2.

**Comment by arekkas** [comment]
Hey thanks for the catch. That's my IDE being annoying. I will fix it asap :)

**Comment by arekkas** [comment]
To be morged as https://github.com/ory-am/ladon/pull/22 and https://github.com/ory-am/hydra/pull/81

**Comment by dancannon** [comment]
Thanks :)
