### ISSUE TITLE
404 in the gitbook  

### ISSUE THREAD

**Issue by allan-simon** [ory-am/hydra#85]
In the page  https://ory-am.gitbooks.io/hydra/content/policy.html

The link to warden examples   `give the Warden examples a read.`   gives a 404 to https://ory-am.gitbooks.io/hydra/content/Ladon%20Repository/

**Comment by arekkas** [comment]
thanks, fixed :)

**Comment by allan-simon** [comment]
same for "warden guide" link in http://docs.hdyra.apiary.io/#reference/warden  :)

**Comment by arekkas** [comment]
fixed that one, too. thanks :)
