### ISSUE TITLE
Creating clients with predefined credentials

### ISSUE THREAD

**Issue by janekolszak** [ory-am/hydra#91]
It would be a nice feature to pass ID/secret pair to hydra clients create.

This is only for development of course. Right now I have to parse .hydra.yml to get the trusted client's credentials. It would be much easier to just have them predefined and hard-coded somewhere.

**Comment by arekkas** [comment]
Some values are already possible to pass:

```
hydra help clients create
This command creates a basic OAuth2 client. Always specify at least one redirect url.

Example:
  hydra clients create -n "my app" -c=[http://localhost/cb] -g [authorization_code] -r [code] -a [core,foobar]

Usage:
  hydra clients create [flags]

Flags:
  -a, --allowed-scopes value   A list of allowed scopes (default [core])
  -c, --callbacks value        REQUIRED list of allowed callback URLs (default [])
  -g, --grant-types value      A list of allowed grant types (default [authorization_code])
      --id string              Give the client this id
  -n, --name string            The client's name
  -r, --response-types value   A list of allowed response types (default [code])

Global Flags:
      --config string     config file (default is $HOME/.hydra.yaml)
      --skip-tls-verify   foolishly accept TLS certificates signed by unkown certificate authorities
```

it makes sense to pass the password as well. The password should however not be set using `--secret=secret` but rather by bool flag `--secret` that prompts for a password

**Comment by arekkas** [comment]
Do you need this feature for `hydra clients create` or for `hydra host` (the initial admin client credentials)?

**Comment by janekolszak** [comment]
`hydra clients create` covers all use cases. I could create the IdP client and possibly some other clients for test purposes (for example the Resource Provider). 

But `hydra host` would be nice as well. There would be only one client for IdP.

**Comment by janekolszak** [comment]
Please don't make it interactive

**Comment by arekkas** [comment]
if it's not interactive, the secret will be stored in bash history, no?

**Comment by arekkas** [comment]
If you worry about scriptability, you can pipe the password:

```
echo "somesecret
" | hydra clients create
```

**Comment by arekkas** [comment]
Hm. I took a little time to research and stumbled upon SSH that does not allow to pipe passwords. As already mentioned, passing passwords to the CLI is a security risk. Read more on this:

* http://stackoverflow.com/questions/6607675/shell-script-password-security-of-command-line-parameters
* http://stackoverflow.com/questions/24454037/pass-a-password-to-ssh-in-pure-bash
* http://serverfault.com/questions/592744/how-to-hide-a-password-passed-as-command-line-argument
* http://unix.stackexchange.com/questions/78734/why-shouldnt-someone-use-passwords-in-the-command-line

> Really, this should be fixed in the application itself. And such applications should be open source, so that fixing the issue in the app itself should be an option. A security related application which makes this kind of mistake might make other mistakes as well, so I wouldn't trust it.

My best guess right now is setting this through env vars:

```
USE_SECRET=123456 hydra clients create ...
```

What do you think @janekolszak ?

**Comment by arekkas** [comment]
Check out https://github.com/ory-am/hydra/commit/9e4e6273e6e18ca0533ea8e89c7228a4894a6380 - it would work like this:

```
FORCE_CLIENT_SECRET=somesupersecretPassword create -n "my app" -c=[http://localhost/cb]
```

**Comment by janekolszak** [comment]
Command line app has to flush stdin before asking for any security related data, so this option is out.
Passing as an argument will be visible in ps, so it's out.
Environment variable will be visible in .bash_history, also out.

The only option I see is to pass a configuration file with a list of clients to create.

**Comment by arekkas** [comment]
> Environment variable will be visible in .bash_history, also out.
> The only option I see is to pass a configuration file with a list of clients to create.

Isn't this the same? The file can also be read. .bash_history is at least always owner-/group-read only

**Comment by arekkas** [comment]
In container environments secrets are usually set using environment variables. I believe that all PaaS (heroku, cloudfoundry, kubernetes...) don't log environment variables. Unless you think otherwise, I believe this is the right choice.

**Comment by janekolszak** [comment]
You can set the right permissions for this file too. You can also remove it after your're done with creating clients. 

What if I need to create couple of clients? 
Env variable would have to be a list.

The configuration and env variable will be on your local laptop anyway. 

This feature isn't for production, it's only for debugging and examples. I'd even allow passing the password via command line argument.

**Comment by arekkas** [comment]
You're right, it's more obvious if it's a file then a side effect (storing it to .bash_history). Thanks for your thoughts :)

**Comment by arekkas** [comment]
@janekolszak I have added this in https://github.com/ory-am/hydra/pull/90/commits/69a54e187d7a7b74aa4681bb0af32d7a1b9a3fb5:

```
go run main.go clients import
Usage:
  hydra clients import <path/to/file.json> [<path/to/other/file.json>...] [flags]

Flags:
  -h, --help   help for import

Global Flags:
      --config string     config file (default is $HOME/.hydra.yaml)
      --skip-tls-verify   foolishly accept TLS certificates signed by unkown certificate authorities
```

please let me know if that's what you wanted

**Comment by janekolszak** [comment]
What's the format of  <path/to/file.json> ?

**Comment by arekkas** [comment]
The format is the one you send to the HTTP API as documented [here](http://docs.hdyra.apiary.io/#reference/oauth2-clients/oauth2-clients-collection)

**Comment by ashic** [comment]
Is there an updated link? The apiary one seems broken.

**Comment by arekkas** [comment]
![image](https://user-images.githubusercontent.com/3372410/33135144-de422e7e-cfa1-11e7-8187-4b3a578b8bc9.png)

:)
