### ISSUE TITLE
Is gopheracademy.com example out of date now?

### ISSUE THREAD

**Issue by faxal** [ory-am/hydra#94]
https://blog.gopheracademy.com/advent-2015/hydra-auth/

In the post it is mentioned  how to create users and using them to authenticate  [here](https://blog.gopheracademy.com/advent-2015/hydra-auth/#oauth2-token-password-grant:62d10e1202aa0bf1f7fc293fa0c6db9f). 

Browsing the source and reading the current documentation I don't see how to do that now.

Is it possible to manage Authentication with Hydra or does it have to be run separately.

**Comment by arekkas** [comment]
Hi @faxal ! The example from gopheracademy is out of date. As part of the rewrite we decided to remove the proprietairy IDP (identity provider) from hydra and let people build their own. If you are interested in writing a generic hydra-friendly IDP let me know. There's a lot of example code out there that would help you :)

Here's the current IDP example: https://github.com/ory-am/hydra-idp-react/

**Comment by arekkas** [comment]
Feel free to reopen if you have further questions or [![Join the chat at https://gitter.im/ory-am/hydra](https://img.shields.io/badge/join-chat-00cc99.svg)](https://gitter.im/ory-am/hydra?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [![Join mailinglist](https://img.shields.io/badge/join-mailinglist-00cc99.svg)](https://groups.google.com/forum/#!forum/ory-hydra/new) :)

**Comment by janekolszak** [comment]
Example in Go: https://github.com/janekolszak/hydra-idp-go

**Comment by arekkas** [comment]
Nice! Let me know if you want me to take a look at it. I have time tomorrow and during the week

**Comment by janekolszak** [comment]
Sure, take a look. I'll implement some production code using this example so all comments are welcomed.

**Comment by arekkas** [comment]
Looks good! You probably already know, but you should add the 
authentication (check session cookie or prompt for user credentials) here:

* https://github.com/janekolszak/hydra-idp-go/blob/master/idp/main.go#L194

One more note - as I've seen that you load the hydra.yml file from 
volume on start up. The hydra.yml file might not be available when hydra 
and hydra-idp-go docker containers are started simoultaneously. Hydra 
needs a little time to generate the keys, connect to db and so on - you 
will either need to watch the hydra.yml file for changes or delay the 
read-in.

Ah, nevermind, just saw that you already do that: 
https://github.com/janekolszak/hydra-idp-go/blob/master/idp/Dockerfile#L10

We need to think of a better way to solve this, e.g. by writing a shell 
script that waits for the hydra port to open and can be added to Dockerfile

Everything else looks good!

Am 04.06.2016 um 20:26 schrieb Jan Olszak:
