### ISSUE TITLE
Add offline scope for refresh tokens

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#97]

**Comment by janekolszak** [comment]
What's a refresh token with an offline scope?

**Comment by arekkas** [comment]
Right now RT are issued always. This is a security weakness. In the future the RT should only be issued when the scope 'offline' is set. This is how most OAuth2 providers do it, like Google and MS 

Gesendet mit meinem HTC

----- Reply message -----
Von: "Jan Olszak" <notifications@github.com>
An: "ory-am/hydra" <hydra@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Author" <author@noreply.github.com>
Betreff: [ory-am/hydra] Add offline scope for refresh tokens (#97)
Datum: Mi., Juni 8, 2016 01:07

What's a refresh token with an offline scope?


---
