### ISSUE TITLE
CLI should have `-dry` option to show what the HTTP request looks like

### ISSUE THREAD

**Issue by arekkas** [ory-am/hydra#99]
Format should be curl. This can be achieved with: https://github.com/moul/http2curl

**Comment by janekolszak** [comment]
Also automatically opening the browser is annoying. It should be disabled by default, not the other way around.

**Comment by arekkas** [comment]
@janekolszak when does that happen? I know there's a bug where this happens when you run the tests but usually the CLI doesn't open the browser window, except `hydra token user`?

**Comment by janekolszak** [comment]
yes, `hydra token user` even has an option to switch this off. I think it would be better to print a curl command: `curl -Lkv "address" `

**Comment by arekkas** [comment]
`curl` isn't installed on Windows. The curl command will be printed when using `-dry` :)

The idea of `hydra token user` is to initiate an exemplary OAuth2 request - I think opening the browser for that is ok, no? I can't really imagine where this command would be useful except for showing an exemplary flow.

**Comment by faxal** [comment]
It was annoying for me too at first, because chromium is my default browser and it doesn't work with chromium because of the certificate issue. 

However it can be disabled in chromium for localhost by putting
`--allow-insecure-localhost` in `~/.config/chromium-flags.conf` or your `$XDG_CONFIG_HOME/chromium-flags.conf`.

**Comment by arekkas** [comment]
```
go run main.go keys create foo123 --dry --skip-tls-verify
Warning: Skipping TLS Certificate Verification.
Could not generate keys: Because you are using the dry option, the request will not be executed. You can execute this command using:

curl -X POST -d "{\"alg\":\"\",\"keys\":null}" -H "Content-Type: application/json" 'https://localhost:4444/keys/foo123
```
